import type { Sku } from './types'

export const blankSku: Sku = {
  id: '',
  code: '',
  name: '',
  category: '滤清系统',
  brand: '',
  partNumber: '',
  nature: 'UNKNOWN',
  origin: '待确认',
  country: '',
  unit: '个',
  specification: '',
  position: '',
  packQuantity: 1,
  imageUrl: '',
  tradePriceMinor: null,
  repairPriceMinor: null,
  notes: '',
  enabled: true,
  version: 0,
  updatedAt: '',
  numbers: [],
  fitments: [],
  stocks: [],
  prices: [],
  supplierQuotes: [],
}
